package com.blockchain.kyc.api.nabu

internal const val NABU_COUNTRIES = "countries"
internal const val NABU_STATES = "states"
internal const val NABU_INITIAL_AUTH = "users"
internal const val NABU_SESSION_TOKEN = "auth"
internal const val NABU_USERS_CURRENT = "users/current"
internal const val NABU_PUT_ADDRESS = "users/current/address"
internal const val NABU_RECORD_COUNTRY = "users/current/country"
internal const val NABU_ONFIDO_API_KEY = "kyc/credentials/onfido"
internal const val NABU_VERIFF_TOKEN = "kyc/credentials/veriff"
internal const val NABU_SUBMIT_VERIFICATION = "kyc/verifications"
internal const val NABU_UPDATE_WALLET_INFO = "users/current/walletInfo"
internal const val NABU_RECOVER_USER = "users/recover"
internal const val NABU_REGISTER_CAMPAIGN = "users/register-campaign"
internal const val NABU_SUPPORTED_DOCUMENTS = "kyc/supported-documents"
internal const val NABU_KYC_TIERS = "kyc/tiers"
